version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6
      POSTGRES_DB: youtube
    ports:
      - '5432:5432'

  api:
    build:
      context: .
    container_name: nest-api
    ports:
      - '4000:4000'
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:6@db:5432/youtube
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
      - ./uploads:/app/uploads:ro
    depends_on:
      - api